#! /bin/bash

# attempt to duplicate s01_setup.py
# FIXME: not handling merging of epochs

set -eo pipefail

# fits dir is /data/legs/rpete/data/ECS/e${epoch}/fits/$ECSID
[ -z "$ECSID" ] && {
    \echo "\$ECSID is not set, exiting" 1>&2
    exit 1
}

[ $# -ge 3 ] || {
    \echo "Usage: $0 t1,t2,... binx biny [epoch1 epoch2 ...]" 1>&2
    exit 1
}

temps=$(sed 's/,/ /g' <<<"$1")
tstr=$(sed 's/,/-/g' <<<"$1")
shift
binx="$1"
shift
biny="$1"
shift
epochs="$@"
echo $epochs

. ~/.bash_aliases
shopt -s expand_aliases extglob nocasematch

#
# CIAO init doesn't work with bash nounset mode
#
reset_u=0
[[ $- =~ u ]] && {
    set +u
    reset_u=1
}
ciao -o
[ $reset_u -eq 1 ] && set -u

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $SCRIPTDIR/tmppdir.sh

extract_spectra() {
    [ $# -eq 1 ] || {
	echo Usage: extract_spectra epoch 1>&2
	return 1
    }

    local epoch=$(printf %03d $((10#"$1")))
    local basedir=/data/legs/rpete/data/ECS/e${epoch}
    local outdir="${basedir}/fits/${ECSID}"
    local merge_indir="${basedir}/merge/${ECSID}"
    local merge_outdir="$outdir/evt2/fpt_${tstr}"
    local merge_lis_outdir="$merge_outdir/merge_lis"
    
    # might have already merged this epoch's evt2 for this temperature range
    [ -d "$merge_outdir" ] || {
	mkdir -p "$merge_lis_outdir"
	for ccd in i{0,1,2,3} s{0,1,2,3,4,5}; do
	    merge_list="$merge_lis_outdir/merge_${ccd}.lis"
	    rm -f "$merge_list"
	    evt2_out="${merge_outdir}/${ccd}.evt2"
	    for t in $temps; do
		evt2_add="${merge_indir}/e${epoch}_${ccd:0:2}_${t}.evt2"
		[ -f "$evt2_add"?(.gz) ] || {
		    echo not found "$evt2_add"?(.gz)
		    continue
		}
		echo "$evt2_add"?(.gz) >> "$merge_list"
	    done
	    [ -f  "$merge_list" ] || continue
	    dmmerge \
		"@${merge_list}[cols -phas,-node_id][subspace -expno]" \
		"$evt2_out" \
		lookupTab=/data/legs/rpete/flight/acis_ecs/data/dmmerge_lookupTab.txt \
		cl+
	    #rm -f "$merge_list"
	done
    }

    spec_dir="$outdir/spec/fpt_${tstr}_${binx}x${biny}y"
    rm -rf "$spec_dir"
    mkdir -p "$spec_dir"
    for ccd in i{0,1,2,3} s{0,1,2,3,4,5}; do
	evt="${merge_outdir}/${ccd}.evt2"
	[ -f "$evt" ] || continue
	echo extracting from $evt
	for x in $(seq 1 $binx 1024); do
	    xl=$(printf %04d $x)
	    xh=$(printf %04d $(( x+binx-1 )))
	    for y in $(seq 1 $biny 1024); do
		yl=$(printf %04d $y)
		yh=$(printf %04d $(( y+biny-1 )))
		inf="${evt}[chipx=${xl}:${xh},chipy=${yl}:${yh}][cols time]"
		punlearn dmstat
		dmstat "$inf" 1>/dev/null
		[ $(pget dmstat out_good) -gt 300 ] && {
		    inf="${evt}[chipx=${xl}:${xh},chipy=${yl}:${yh}][bin pi=1:1024:1]"
		    outf="${spec_dir}/${ccd}_${xl}-${xh}x_${yl}-${yh}y.pi"
		    punlearn dmextract
		    dmextract "$inf" "$outf" cl+
		}
	    done
	done
    done
    return 0
}

for epoch in $epochs; do
    extract_spectra $epoch
done

