#! /bin/bash

set -eo pipefail

[ $# -ge 1 ] || {
    echo "Usage: $0 epoch1 epoch2 ..." 1>&2
    exit 1
}
epochs="$@"


. ~/.bash_aliases
shopt -s expand_aliases nocasematch

ciao

srcdir=/data/legs/rpete/flight/acis_ecs/src/

true && {
    for epoch in $epochs; do
	epoch=$(printf %03d $((10#"$epoch")))
	rm -rf /data/legs/rpete/data/ECS/e$epoch/fits/fits
	for ccd in i{0,1,2,3} s{0,1,2,3,4,5} s1_noCTI s3_noCTI; do
	    echo $epoch $ccd
	done
    done | parallel -j 16 --colsep ' ' python $srcdir/fit_spectra.py 120,119,118 yes 256 256
} || {
    sname=fit_epochs_parallel_ccd #_$(tr -dc A-Za-z0-9 </dev/urandom | head -c 6; echo)
    for epoch in $epochs; do
	epoch=$(printf %03d $((10#"$epoch")))
	rm -rf /data/legs/rpete/data/ECS/e$epoch/fits/fits
	screen -dmS $sname
	for ccd in i{0,1,2,3} s{0,1,2,3,4,5} s1_noCTI s3_noCTI; do
	    screen -S $sname -X screen bash -c "python $srcdir/fit_spectra.py 120,119,118 yes 256 256 $epoch $ccd; #exec bash"
	done
	# wait until all of the screens are done
	screen -S $sname -p0 -X kill
	screen -rS $sname
    done
}
