#! /bin/bash

set -eo pipefail

# fits dir is /data/legs/rpete/data/ECS/e${epoch}/fits/$ECSID/fits
[ -z "$ECSID" ] && {
    \echo "\$ECSID is not set, exiting" 1>&2
    exit 1
}

[ $# -ge 3 ] || {
    echo "Usage: $0 tstr binx biny [epoch1 epoch2 ...]" 1>&2
    exit 1
}

tstr=$(sed 's/,/-/g' <<<"$1")
shift
binx="$1"
shift
biny="$1"
shift

epochs="$@"

. ~/.bash_aliases
shopt -s expand_aliases nocasematch

ciao

srcdir=/data/legs/rpete/flight/acis_ecs/src
pdfpre="/data/legs/rpete/data/ECS/e"
pdfpost="/fits/$ECSID/fits/fpt_${tstr}_${binx}x${biny}y/figs/"

epochs=$(bash -c "for e in $epochs; do printf '%03d ' \$e; done")
ccds=$( echo i{0,1,2,3} s{0,1,2,3,4,5} )
parallel -j 16 python "$srcdir/fit_spectrum_narrowwin.py" -p "$pdfpre"{1}"$pdfpost"{2}.pdf $tstr $binx $biny {1} {2} ::: $epochs ::: $ccds

