#! /bin/bash

set -eo pipefail

epochs="$@"

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

[ $# -eq 1 ] && {
    indirs=$(echo /data/legs/rpete/data/ECS/e$(printf %03d $((10#$1)))/[0-9][0-9][0-9][0-9][0-9])
} || {
    eglob=$(perl -le 'print("{", join(",", map { sprintf "%03d", $_ } @ARGV),"}");' $epochs)
    indirs=$(bash -c 'echo '/data/legs/rpete/data/ECS/e$eglob/[0-9][0-9][0-9][0-9][0-9])
}

process_obsids="$SCRIPTDIR/process_obsids"
parallel -j 32 "$process_obsids" ::: $indirs
