#! /bin/bash

# first attempt at duplicating
# /home/rpete/hal9000/ECS_fits/scripts/s999_repro.py

set -eo pipefail

# merge dir is /data/legs/rpete/data/ECS/e${epoch}/merge/$ECSID
[ -z "$ECSID" ] && {
    \echo "\$ECSID is not set, exiting" 1>&2
    exit 1
}

epochs="$@"

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

process_obsids="$SCRIPTDIR/process_obsids"

eglob=$(perl -le 'print("{", join(",", map { sprintf "%03d", $_ } @ARGV),"}");' $epochs)
indirs=$(bash -c 'echo '/data/legs/rpete/data/ECS/e$eglob/[0-9][0-9][0-9][0-9][0-9])
echo $indirs

parallel -j 32 "$process_obsids" ::: $indirs
